language: go

node_js:
  - 8

go:
  - 1.9

os:
  - linux

cache:
  directories:
    - ~/.npm
    - ~/.cache

before_install: if [[ `npm -v` != 5.7* ]]; then npm i -g npm@5; fi

install:
  - go get -v github.com/revel/cmd/revel
  - go get -v github.com/kardianos/govendor
  - npm ci

before_script:
  - revel run github.com/anikitenko/mini-sftp-client &

script:
  - govendor sync
  - $(npm bin)/cypress run --record